version: 2.1
jobs:
  build:
      steps:
      - checkout
      - run: echo "master"
  test:
    steps:
      - checkout
      - run: echo "hello world"
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
